# Generated by Django 6.0.3 on 2026-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PowerBIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("powerbi_report_id", models.CharField(max_length=120)),
                ("workspace_id", models.CharField(max_length=120)),
                ("dataset_id", models.CharField(blank=True, max_length=120)),
                ("embed_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "allowed_roles",
                    models.CharField(
                        blank=True, help_text="Comma separated role names", max_length=255
                    ),
                ),
                ("feature_flag", models.CharField(blank=True, max_length=80)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "powerbi_reports",
                "ordering": ["report_group__sort_order", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyReportGroupSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "powerbi_property_report_group_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="ReportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("visibility_flags", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "powerbi_report_groups",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportViewAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("success", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "powerbi_report_view_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
