# Generated by Django 6.0.3 on 2026-04-04 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("powerbiembedded", "0001_initial"),
        ("propertycore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="powerbireport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="powerbireport",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyreportgroupsubscription",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_group_subscriptions",
                to="propertycore.property",
            ),
        ),
        migrations.AddField(
            model_name="reportgroup",
            name="properties",
            field=models.ManyToManyField(
                related_name="report_groups",
                through="powerbiembedded.PropertyReportGroupSubscription",
                to="propertycore.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyreportgroupsubscription",
            name="report_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_subscriptions",
                to="powerbiembedded.reportgroup",
            ),
        ),
        migrations.AddField(
            model_name="powerbireport",
            name="report_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="powerbiembedded.reportgroup",
            ),
        ),
        migrations.AddField(
            model_name="reportviewauditlog",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="propertycore.property",
            ),
        ),
        migrations.AddField(
            model_name="reportviewauditlog",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_audits",
                to="powerbiembedded.powerbireport",
            ),
        ),
        migrations.AddField(
            model_name="reportviewauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyreportgroupsubscription",
            unique_together={("property", "report_group")},
        ),
    ]
