# Generated by Django 6.0.3 on 2026-04-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powerbiembedded", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportgroup",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
