from apps.settings.mappings.models import (
    BookingSourceCategory,
    BookingSourceDetail,
    BookingSourceGroup,
    BookingSourceMapping,
    CompanyCategory,
    CompanyDetail,
    CompanyGroup,
    CompanyMapping,
    CompetitorCategory,
    CompetitorDetail,
    CompetitorGroup,
    CompetitorMapping,
    DayOfWeekGroup,
    DayOfWeekMapping,
    GuestCountryCategory,
    GuestCountryDetail,
    GuestCountryGroup,
    GuestCountryMapping,
    LoyaltyCategory,
    LoyaltyDetail,
    LoyaltyGroup,
    LoyaltyMapping,
    OriginCategory,
    OriginDetail,
    OriginGroup,
    OriginMapping,
    PackageCategory,
    PackageDetail,
    PackageGroup,
    PackageMapping,
    RateCodeDetail,
    # RateCodeCategory,
    # RateCodeGroup,
    # RateCodeMapping,
    RoomTypeCategory,
    RoomTypeDetail,
    RoomTypeGroup,
    RoomTypeMapping,
    SegmentMapping,
    SegmentCategory,
    SegmentDetail,
    SegmentGroup,
    TravelAgentCategory,
    TravelAgentDetail,
    TravelAgentGroup,
    TravelAgentMapping,
)

from apps.settings.mappings.forms.hierarchy import (
    BookingSourceCategoryForm,
    BookingSourceDetailForm,
    BookingSourceGroupForm,
    BookingSourceMappingForm,
    CompanyCategoryForm,
    CompanyDetailForm,
    CompanyGroupForm,
    CompanyMappingForm,
    CompetitorCategoryForm,
    CompetitorDetailForm,
    CompetitorGroupForm,
    CompetitorMappingForm,
    DayOfWeekGroupForm,
    DayOfWeekMappingForm,
    GuestCountryCategoryForm,
    GuestCountryDetailForm,
    GuestCountryGroupForm,
    GuestCountryMappingForm,
    LoyaltyCategoryForm,
    LoyaltyDetailForm,
    LoyaltyGroupForm,
    LoyaltyMappingForm,
    OriginCategoryForm,
    OriginDetailForm,
    OriginGroupForm,
    OriginMappingForm,
    PackageCategoryForm,
    PackageDetailForm,
    PackageGroupForm,
    PackageMappingForm,
    RateCodeDetailForm,
    # RateCodeCategoryForm,
    # RateCodeGroupForm,
    # RateCodeMappingForm,
    RoomTypeCategoryForm,
    RoomTypeDetailForm,
    RoomTypeGroupForm,
    RoomTypeMappingForm,
    SegmentCategoryForm,
    SegmentDetailForm,
    SegmentForm,
    SegmentGroupForm,
    TravelAgentCategoryForm,
    TravelAgentDetailForm,
    TravelAgentGroupForm,
    TravelAgentMappingForm,
)

def build_domain_config(
    *,
    key,
    label,
    description,
    color,
    icon,
    group_model,
    category_model,
    mapping_model,
    detail_model,
    group_form,
    category_form,
    mapping_form,
    detail_form,
    has_group=True,
    has_category=True,
    has_details=True,
    has_mapping=True,
    image=None,
):
    return {
        'key': key,
        'label': label,
        'description': description,
        'color': color,
        'icon': icon,
        'image': image,
        'card_border_class': f'hover:border-{color}-300 dark:hover:border-{color}-700',
        'card_ring_class': f'hover:ring-{color}-200 dark:hover:ring-{color}-800',
        'top_bar_class': f'bg-{color}-500',
        'icon_bg_class': f'bg-{color}-100 dark:bg-{color}-500/10',
        'icon_text_class': f'text-{color}-600 dark:text-{color}-400',
        'title_hover_class': f'group-hover:text-{color}-700 dark:group-hover:text-{color}-400',
        'arrow_hover_class': (
            f'group-hover:bg-{color}-50 '
            f'group-hover:text-{color}-600 '
            f'group-hover:border-{color}-300 '
            f'dark:group-hover:bg-{color}-500/10 '
            f'dark:group-hover:text-{color}-400 '
            f'dark:group-hover:border-{color}-700'
        ),
        'button_class': f'bg-{color}-500 dark:bg-{color}-400',
        'button_hover_class': f'hover:bg-{color}-600 dark:hover:bg-{color}-300',
        'has_group': has_group,
        'has_category': has_category,
        'has_mapping': has_mapping,
        'has_details': has_details,
        'group_model': group_model,
        'category_model': category_model,
        'mapping_model': mapping_model,
        'detail_model': detail_model,
        'group_form': group_form,
        'category_form': category_form,
        'mapping_form': mapping_form,
        'detail_form': detail_form,
    }



MAPPING_DOMAIN_REGISTRY = {
    'segmentations': build_domain_config(
        key='segmentations',
        label='Segmentation',
        description='Organize segmentation into groups, categories, mappings, and source-level details.',
        color='orange',
        icon='fas fa-layer-group',
        group_model=SegmentGroup,
        category_model=SegmentCategory,
        mapping_model=SegmentMapping,
        detail_model=SegmentDetail,
        group_form=SegmentGroupForm,
        category_form=SegmentCategoryForm,
        mapping_form=SegmentForm,
        detail_form=SegmentDetailForm,
    ),
    'room-types': build_domain_config(
        key='room-types',
        label='Room Type',
        description='Define room type structures through groups, categories, mappings, and source details.',
        color='sky',
        icon='fas fa-bed',
        group_model=RoomTypeGroup,
        category_model=RoomTypeCategory,
        mapping_model=RoomTypeMapping,
        detail_model=RoomTypeDetail,
        group_form=RoomTypeGroupForm,
        category_form=RoomTypeCategoryForm,
        mapping_form=RoomTypeMappingForm,
        detail_form=RoomTypeDetailForm,
    ),
    'packages': build_domain_config(
        key='packages',
        label='Package',
        description='Organize packages into groups, categories, mappings, and source-level detail records.',
        color='emerald',
        icon='fas fa-box-open',
        group_model=PackageGroup,
        category_model=PackageCategory,
        mapping_model=PackageMapping,
        detail_model=PackageDetail,
        group_form=PackageGroupForm,
        category_form=PackageCategoryForm,
        mapping_form=PackageMappingForm,
        detail_form=PackageDetailForm,
    ),
    'rate-codes': build_domain_config(
        key='rate-codes',
        label='Rate Code',
        description='Structure rate codes through hierarchy and source details for stronger pricing analysis.',
        color='violet',
        icon='fas fa-tags',
        has_category=False,
        has_group=False,
        has_mapping=False,
        # group_model=RateCodeGroup,
        # category_model=RateCodeCategory,
        # group_form=RateCodeGroupForm,
        # category_form=RateCodeCategoryForm,
        mapping_model=None,
        mapping_form=None,
        group_model=None,
        category_model=None,
        group_form=None,
        category_form=None,
        detail_model=RateCodeDetail,
        detail_form=RateCodeDetailForm,
    ),
    'travel-agents': build_domain_config(
        key='travel-agents',
        label='Travel Agent',
        description='Organize travel agent relationships using groups, categories, mappings, and raw detail values.',
        color='cyan',
        icon='fas fa-plane-departure',
        group_model=TravelAgentGroup,
        category_model=TravelAgentCategory,
        mapping_model=TravelAgentMapping,
        detail_model=TravelAgentDetail,
        group_form=TravelAgentGroupForm,
        category_form=TravelAgentCategoryForm,
        mapping_form=TravelAgentMappingForm,
        detail_form=TravelAgentDetailForm,
    ),
    'guest-countries': build_domain_config(
        key='guest-countries',
        label='Guest Country',
        description='Map guest country data with a full hierarchy for cleaner market and source analysis.',
        color='amber',
        icon='fas fa-globe',
        group_model=GuestCountryGroup,
        category_model=GuestCountryCategory,
        mapping_model=GuestCountryMapping,
        detail_model=GuestCountryDetail,
        group_form=GuestCountryGroupForm,
        category_form=GuestCountryCategoryForm,
        mapping_form=GuestCountryMappingForm,
        detail_form=GuestCountryDetailForm,
    ),
    'companies': build_domain_config(
        key='companies',
        label='Company',
        description='Classify company business with consistent hierarchy and detailed source-level mapping.',
        color='blue',
        icon='fas fa-building',
        group_model=CompanyGroup,
        category_model=CompanyCategory,
        mapping_model=CompanyMapping,
        detail_model=CompanyDetail,
        group_form=CompanyGroupForm,
        category_form=CompanyCategoryForm,
        mapping_form=CompanyMappingForm,
        detail_form=CompanyDetailForm,
    ),
    'day-of-week': build_domain_config(
        key='day-of-week',
        label='Day of Week',
        description='Manage weekday structures using hierarchy-based mappings and source details.',
        color='indigo',
        icon='fas fa-calendar-day',
        has_category=False,
        has_details=False,
        group_model=DayOfWeekGroup,
        category_model=None,
        mapping_model=DayOfWeekMapping,
        detail_model=None,
        group_form=DayOfWeekGroupForm,
        category_form=None,
        mapping_form=DayOfWeekMappingForm,
        detail_form=None,
    ),
    'booking-sources': build_domain_config(
        key='booking-sources',
        label='Booking Source',
        description='Organize booking channels into groups, categories, mappings, and source details.',
        color='rose',
        icon='fas fa-network-wired',
        group_model=BookingSourceGroup,
        category_model=BookingSourceCategory,
        mapping_model=BookingSourceMapping,
        detail_model=BookingSourceDetail,
        group_form=BookingSourceGroupForm,
        category_form=BookingSourceCategoryForm,
        mapping_form=BookingSourceMappingForm,
        detail_form=BookingSourceDetailForm,
    ),
    'origins': build_domain_config(
        key='origins',
        label='Origin',
        description='Map reservation origins with a full hierarchy for better source attribution and reporting.',
        color='teal',
        icon='fas fa-route',
        group_model=OriginGroup,
        category_model=OriginCategory,
        mapping_model=OriginMapping,
        detail_model=OriginDetail,
        group_form=OriginGroupForm,
        category_form=OriginCategoryForm,
        mapping_form=OriginMappingForm,
        detail_form=OriginDetailForm,
    ),
    'competitors': build_domain_config(
        key='competitors',
        label='Competitor',
        description='Track competitors using structured hierarchy and detailed source records.',
        color='red',
        icon='fas fa-trophy',
        group_model=CompetitorGroup,
        category_model=CompetitorCategory,
        mapping_model=CompetitorMapping,
        detail_model=CompetitorDetail,
        group_form=CompetitorGroupForm,
        category_form=CompetitorCategoryForm,
        mapping_form=CompetitorMappingForm,
        detail_form=CompetitorDetailForm,
    ),
    'loyalties': build_domain_config(
        key='loyalties',
        label='Loyalty',
        description='Organize loyalty data into groups, categories, mappings, and source details.',
        color='pink',
        icon='fas fa-crown',
        group_model=LoyaltyGroup,
        category_model=LoyaltyCategory,
        mapping_model=LoyaltyMapping,
        detail_model=LoyaltyDetail,
        group_form=LoyaltyGroupForm,
        category_form=LoyaltyCategoryForm,
        mapping_form=LoyaltyMappingForm,
        detail_form=LoyaltyDetailForm,
    ),
}


def get_mapping_domain(domain_key):
    config = MAPPING_DOMAIN_REGISTRY[domain_key].copy()

    config.setdefault('has_group', True)
    config.setdefault('has_category', True)
    config.setdefault('has_details', True)
    config.setdefault('has_mapping', True)

    config.setdefault('group_model', None)
    config.setdefault('category_model', None)
    config.setdefault('mapping_model', None)
    config.setdefault('detail_model', None)

    config.setdefault('group_form', None)
    config.setdefault('category_form', None)
    config.setdefault('mapping_form', None)
    config.setdefault('detail_form', None)

    config.setdefault('color', 'orange')
    config.setdefault('icon', 'fas fa-folder')
    config.setdefault('image', None)
    config.setdefault('card_border_class', 'hover:border-orange-300 dark:hover:border-orange-700')
    config.setdefault('card_ring_class', 'hover:ring-orange-200 dark:hover:ring-orange-800')
    config.setdefault('top_bar_class', 'bg-orange-500')
    config.setdefault('icon_bg_class', 'bg-orange-100 dark:bg-orange-500/10')
    config.setdefault('icon_text_class', 'text-orange-600 dark:text-orange-400')
    config.setdefault('title_hover_class', 'group-hover:text-orange-700 dark:group-hover:text-orange-400')
    config.setdefault(
        'arrow_hover_class',
        'group-hover:bg-orange-50 group-hover:text-orange-600 group-hover:border-orange-300 '
        'dark:group-hover:bg-orange-500/10 dark:group-hover:text-orange-400 dark:group-hover:border-orange-700'
    )
    config.setdefault('button_class', 'bg-orange-600 dark:bg-orange-500')
    config.setdefault('button_hover_class', 'hover:bg-orange-700 dark:hover:bg-orange-400')

    return config

