from apps.settings.mappings.models import (
    BookingSourceCategory,
    BookingSourceDetail,
    BookingSourceGroup,
    BookingSourceMapping,
    CompanyCategory,
    CompanyDetail,
    CompanyGroup,
    CompanyMapping,
    CompetitorCategory,
    CompetitorDetail,
    CompetitorGroup,
    CompetitorMapping,
    DayOfWeekGroup,
    DayOfWeekMapping,
    GuestCountryCategory,
    GuestCountryDetail,
    GuestCountryGroup,
    GuestCountryMapping,
    LoyaltyCategory,
    LoyaltyDetail,
    LoyaltyGroup,
    LoyaltyMapping,
    OriginCategory,
    OriginDetail,
    OriginGroup,
    OriginMapping,
    PackageCategory,
    PackageDetail,
    PackageGroup,
    PackageMapping,
    RateCodeCategory,
    RateCodeDetail,
    RateCodeGroup,
    RateCodeMapping,
    RoomTypeCategory,
    RoomTypeDetail,
    RoomTypeGroup,
    RoomTypeMapping,
    SegmentMapping,
    SegmentCategory,
    SegmentDetail,
    SegmentGroup,
    TravelAgentCategory,
    TravelAgentDetail,
    TravelAgentGroup,
    TravelAgentMapping,
)

from apps.settings.mappings.forms.hierarchy import (
    BookingSourceCategoryForm,
    BookingSourceDetailForm,
    BookingSourceGroupForm,
    BookingSourceMappingForm,
    CompanyCategoryForm,
    CompanyDetailForm,
    CompanyGroupForm,
    CompanyMappingForm,
    CompetitorCategoryForm,
    CompetitorDetailForm,
    CompetitorGroupForm,
    CompetitorMappingForm,
    DayOfWeekGroupForm,
    DayOfWeekMappingForm,
    GuestCountryCategoryForm,
    GuestCountryDetailForm,
    GuestCountryGroupForm,
    GuestCountryMappingForm,
    LoyaltyCategoryForm,
    LoyaltyDetailForm,
    LoyaltyGroupForm,
    LoyaltyMappingForm,
    OriginCategoryForm,
    OriginDetailForm,
    OriginGroupForm,
    OriginMappingForm,
    PackageCategoryForm,
    PackageDetailForm,
    PackageGroupForm,
    PackageMappingForm,
    RateCodeCategoryForm,
    RateCodeDetailForm,
    RateCodeGroupForm,
    RateCodeMappingForm,
    RoomTypeCategoryForm,
    RoomTypeDetailForm,
    RoomTypeGroupForm,
    RoomTypeMappingForm,
    SegmentCategoryForm,
    SegmentDetailForm,
    SegmentForm,
    SegmentGroupForm,
    TravelAgentCategoryForm,
    TravelAgentDetailForm,
    TravelAgentGroupForm,
    TravelAgentMappingForm,
)

def build_domain_config(
    *,
    key,
    label,
    description,
    color,
    icon,
    group_model,
    category_model,
    mapping_model,
    detail_model,
    group_form,
    category_form,
    mapping_form,
    detail_form,
    has_group=True,
    has_category=True,
    has_details=True,
    image=None,
):
    return {
        'key': key,
        'label': label,
        'description': description,
        'color': color,
        'icon': icon,
        'image': image,
        'card_border_class': f'hover:border-{color}-300 dark:hover:border-{color}-700',
        'card_ring_class': f'hover:ring-{color}-200 dark:hover:ring-{color}-800',
        'top_bar_class': f'bg-{color}-500',
        'icon_bg_class': f'bg-{color}-100 dark:bg-{color}-500/10',
        'icon_text_class': f'text-{color}-600 dark:text-{color}-400',
        'title_hover_class': f'group-hover:text-{color}-700 dark:group-hover:text-{color}-400',
        'arrow_hover_class': (
            f'group-hover:bg-{color}-50 '
            f'group-hover:text-{color}-600 '
            f'group-hover:border-{color}-300 '
            f'dark:group-hover:bg-{color}-500/10 '
            f'dark:group-hover:text-{color}-400 '
            f'dark:group-hover:border-{color}-700'
        ),
        'button_class': f'bg-{color}-500 dark:bg-{color}-400',
        'button_hover_class': f'hover:bg-{color}-600 dark:hover:bg-{color}-300',
        'has_group': has_group,
        'has_category': has_category,
        'has_details': has_details,
        'group_model': group_model,
        'category_model': category_model,
        'mapping_model': mapping_model,
        'detail_model': detail_model,
        'group_form': group_form,
        'category_form': category_form,
        'mapping_form': mapping_form,
        'detail_form': detail_form,
    }



MAPPING_DOMAIN_REGISTRY = {
    'segmentations': build_domain_config(
        key='segmentations',
        label='Segmentation',
        description='Organize segmentation into groups, categories, mappings, and source-level details.',
        color='orange',
        icon='fas fa-layer-group',
        group_model=SegmentGroup,
        category_model=SegmentCategory,
        mapping_model=SegmentMapping,
        detail_model=SegmentDetail,
        group_form=SegmentGroupForm,
        category_form=SegmentCategoryForm,
        mapping_form=SegmentForm,
        detail_form=SegmentDetailForm,
    ),
    'room-types': build_domain_config(
        key='room-types',
        label='Room Type',
        description='Define room type structures through groups, categories, mappings, and source details.',
        color='sky',
        icon='fas fa-bed',
        group_model=RoomTypeGroup,
        category_model=RoomTypeCategory,
        mapping_model=RoomTypeMapping,
        detail_model=RoomTypeDetail,
        group_form=RoomTypeGroupForm,
        category_form=RoomTypeCategoryForm,
        mapping_form=RoomTypeMappingForm,
        detail_form=RoomTypeDetailForm,
    ),
    'packages': build_domain_config(
        key='packages',
        label='Package',
        description='Organize packages into groups, categories, mappings, and source-level detail records.',
        color='emerald',
        icon='fas fa-box-open',
        group_model=PackageGroup,
        category_model=PackageCategory,
        mapping_model=PackageMapping,
        detail_model=PackageDetail,
        group_form=PackageGroupForm,
        category_form=PackageCategoryForm,
        mapping_form=PackageMappingForm,
        detail_form=PackageDetailForm,
    ),
    'rate-codes': build_domain_config(
        key='rate-codes',
        label='Rate Code',
        description='Structure rate codes through hierarchy and source details for stronger pricing analysis.',
        color='violet',
        icon='fas fa-tags',
        group_model=RateCodeGroup,
        category_model=RateCodeCategory,
        mapping_model=RateCodeMapping,
        detail_model=RateCodeDetail,
        group_form=RateCodeGroupForm,
        category_form=RateCodeCategoryForm,
        mapping_form=RateCodeMappingForm,
        detail_form=RateCodeDetailForm,
    ),
    'travel-agents': build_domain_config(
        key='travel-agents',
        label='Travel Agent',
        description='Organize travel agent relationships using groups, categories, mappings, and raw detail values.',
        color='cyan',
        icon='fas fa-plane-departure',
        group_model=TravelAgentGroup,
        category_model=TravelAgentCategory,
        mapping_model=TravelAgentMapping,
        detail_model=TravelAgentDetail,
        group_form=TravelAgentGroupForm,
        category_form=TravelAgentCategoryForm,
        mapping_form=TravelAgentMappingForm,
        detail_form=TravelAgentDetailForm,
    ),
    'guest-countries': build_domain_config(
        key='guest-countries',
        label='Guest Country',
        description='Map guest country data with a full hierarchy for cleaner market and source analysis.',
        color='amber',
        icon='fas fa-globe',
        group_model=GuestCountryGroup,
        category_model=GuestCountryCategory,
        mapping_model=GuestCountryMapping,
        detail_model=GuestCountryDetail,
        group_form=GuestCountryGroupForm,
        category_form=GuestCountryCategoryForm,
        mapping_form=GuestCountryMappingForm,
        detail_form=GuestCountryDetailForm,
    ),
    'companies': build_domain_config(
        key='companies',
        label='Company',
        description='Classify company business with consistent hierarchy and detailed source-level mapping.',
        color='blue',
        icon='fas fa-building',
        group_model=CompanyGroup,
        category_model=CompanyCategory,
        mapping_model=CompanyMapping,
        detail_model=CompanyDetail,
        group_form=CompanyGroupForm,
        category_form=CompanyCategoryForm,
        mapping_form=CompanyMappingForm,
        detail_form=CompanyDetailForm,
    ),
    'day-of-week': build_domain_config(
        key='day-of-week',
        label='Day of Week',
        description='Manage weekday structures using hierarchy-based mappings and source details.',
        color='indigo',
        icon='fas fa-calendar-day',
        has_category=False,
        has_details=False,
        group_model=DayOfWeekGroup,
        category_model=None,
        mapping_model=DayOfWeekMapping,
        detail_model=None,
        group_form=DayOfWeekGroupForm,
        category_form=None,
        mapping_form=DayOfWeekMappingForm,
        detail_form=None,
    ),
    'booking-sources': build_domain_config(
        key='booking-sources',
        label='Booking Source',
        description='Organize booking channels into groups, categories, mappings, and source details.',
        color='rose',
        icon='fas fa-network-wired',
        group_model=BookingSourceGroup,
        category_model=BookingSourceCategory,
        mapping_model=BookingSourceMapping,
        detail_model=BookingSourceDetail,
        group_form=BookingSourceGroupForm,
        category_form=BookingSourceCategoryForm,
        mapping_form=BookingSourceMappingForm,
        detail_form=BookingSourceDetailForm,
    ),
    'origins': build_domain_config(
        key='origins',
        label='Origin',
        description='Map reservation origins with a full hierarchy for better source attribution and reporting.',
        color='teal',
        icon='fas fa-route',
        group_model=OriginGroup,
        category_model=OriginCategory,
        mapping_model=OriginMapping,
        detail_model=OriginDetail,
        group_form=OriginGroupForm,
        category_form=OriginCategoryForm,
        mapping_form=OriginMappingForm,
        detail_form=OriginDetailForm,
    ),
    'competitors': build_domain_config(
        key='competitors',
        label='Competitor',
        description='Track competitors using structured hierarchy and detailed source records.',
        color='red',
        icon='fas fa-trophy',
        group_model=CompetitorGroup,
        category_model=CompetitorCategory,
        mapping_model=CompetitorMapping,
        detail_model=CompetitorDetail,
        group_form=CompetitorGroupForm,
        category_form=CompetitorCategoryForm,
        mapping_form=CompetitorMappingForm,
        detail_form=CompetitorDetailForm,
    ),
    'loyalties': build_domain_config(
        key='loyalties',
        label='Loyalty',
        description='Organize loyalty data into groups, categories, mappings, and source details.',
        color='pink',
        icon='fas fa-crown',
        group_model=LoyaltyGroup,
        category_model=LoyaltyCategory,
        mapping_model=LoyaltyMapping,
        detail_model=LoyaltyDetail,
        group_form=LoyaltyGroupForm,
        category_form=LoyaltyCategoryForm,
        mapping_form=LoyaltyMappingForm,
        detail_form=LoyaltyDetailForm,
    ),
}


def get_mapping_domain(domain_key):
    config = MAPPING_DOMAIN_REGISTRY[domain_key].copy()

    config.setdefault('has_group', True)
    config.setdefault('has_category', True)
    config.setdefault('has_details', True)

    config.setdefault('group_model', None)
    config.setdefault('category_model', None)
    config.setdefault('mapping_model', None)
    config.setdefault('detail_model', None)

    config.setdefault('group_form', None)
    config.setdefault('category_form', None)
    config.setdefault('mapping_form', None)
    config.setdefault('detail_form', None)

    config.setdefault('color', 'orange')
    config.setdefault('icon', 'fas fa-folder')
    config.setdefault('image', None)
    config.setdefault('card_border_class', 'hover:border-orange-300 dark:hover:border-orange-700')
    config.setdefault('card_ring_class', 'hover:ring-orange-200 dark:hover:ring-orange-800')
    config.setdefault('top_bar_class', 'bg-orange-500')
    config.setdefault('icon_bg_class', 'bg-orange-100 dark:bg-orange-500/10')
    config.setdefault('icon_text_class', 'text-orange-600 dark:text-orange-400')
    config.setdefault('title_hover_class', 'group-hover:text-orange-700 dark:group-hover:text-orange-400')
    config.setdefault(
        'arrow_hover_class',
        'group-hover:bg-orange-50 group-hover:text-orange-600 group-hover:border-orange-300 '
        'dark:group-hover:bg-orange-500/10 dark:group-hover:text-orange-400 dark:group-hover:border-orange-700'
    )
    config.setdefault('button_class', 'bg-orange-600 dark:bg-orange-500')
    config.setdefault('button_hover_class', 'hover:bg-orange-700 dark:hover:bg-orange-400')

    return config


# from bi.apps.settings.mappings.forms.common_ import (
#     RoomTypeGroupForm,
#     RoomTypeMappingForm,
#     PackageGroupForm,
#     PackageMappingForm,
#     RateCodeGroupForm,
#     RateCodeMappingForm,
#     TravelAgentGroupForm,
#     TravelAgentMappingForm,
#     GuestCountryGroupForm,
#     GuestCountryMappingForm,
#     CompanyGroupForm,
#     CompanyMappingForm,
#     DayOfWeekGroupForm,
#     DayOfWeekMappingForm,
#     OriginGroupForm,
#     OriginMappingForm,
#     CompetitorGroupForm,
#     CompetitorMappingForm,
#     LoyaltyGroupForm,
#     LoyaltyMappingForm,
# )
# from apps.settings.mappings.forms.segmentations import (
#     SegmentGroupForm,
#     SegmentCategoryForm,
#     SegmentForm,
#     SegmentDetailForm,
# )

# from apps.settings.mappings.forms.hierarchy import (
#     BookingSourceGroupForm,
#     BookingSourceCategoryForm,
#     BookingSourceMappingForm,
# )

# from apps.settings.mappings.models import (
#     RoomTypeGroup,
#     RoomTypeMapping,
#     PackageGroup,
#     PackageMapping,
#     RateCodeGroup,
#     RateCodeMapping,
#     TravelAgentGroup,
#     TravelAgentMapping,
#     GuestCountryGroup,
#     GuestCountryMapping,
#     CompanyGroup,
#     CompanyMapping,
#     DayOfWeekGroup,
#     DayOfWeekMapping,
#     BookingSourceGroup,
#     BookingSourceCategory,
#     BookingSourceMapping,
#     OriginGroup,
#     OriginMapping,
#     CompetitorGroup,
#     CompetitorMapping,
#     LoyaltyGroup,
#     LoyaltyMapping,
#     SegmentGroup,
#     SegmentCategory,
#     Segment,
#     SegmentDetail,
# )


# MAPPING_DOMAIN_REGISTRY = {
#     'segmentations': {
#         'key': 'segmentations',
#         'label': 'Market Segmentation',
#         'description': 'Organize segmentation into groups, categories, segments, and source-level details.',
#         'color': 'orange',
#         'icon': 'fas fa-layer-group',
#         'image': None, #'mappings/domains/segmentations.jpg',
#         'card_border_class': 'hover:border-orange-300 dark:hover:border-orange-700',
#         'card_ring_class': 'hover:ring-orange-200 dark:hover:ring-orange-800',
#         'top_bar_class': 'bg-orange-500',
#         'icon_bg_class': 'bg-orange-100 dark:bg-orange-500/10',
#         'icon_text_class': 'text-orange-600 dark:text-orange-400',
#         'title_hover_class': 'group-hover:text-orange-700 dark:group-hover:text-orange-400',
#         'arrow_hover_class': 'group-hover:bg-orange-50 group-hover:text-orange-600 group-hover:border-orange-300 dark:group-hover:bg-orange-500/10 dark:group-hover:text-orange-400 dark:group-hover:border-orange-700',
#         'button_class': 'bg-orange-600 dark:bg-orange-500',
#         'button_hover_class': 'hover:bg-orange-700 dark:hover:bg-orange-400',
#         'has_group': True,
#         'has_category': True,
#         'has_details': True,
#         'group_model': SegmentGroup,
#         'category_model': SegmentCategory,
#         'mapping_model': Segment,
#         'detail_model': SegmentDetail,
#         'group_form': SegmentGroupForm,
#         'category_form': SegmentCategoryForm,
#         'mapping_form': SegmentForm,
#         'detail_form': SegmentDetailForm,
#     },
#     'room-types': {
#         'key': 'room-types',
#         'label': 'Room Type',
#         'description': 'Define room categories and pricing relationships to keep inventory structured and easy to analyze.',
#         'color': 'sky',
#         'icon': 'fas fa-bed',
#         'image': None, #'mappings/domains/room-types.jpg',
#         'card_border_class': 'hover:border-sky-300 dark:hover:border-sky-700',
#         'card_ring_class': 'hover:ring-sky-200 dark:hover:ring-sky-800',
#         'top_bar_class': 'bg-sky-500',
#         'icon_bg_class': 'bg-sky-100 dark:bg-sky-500/10',
#         'icon_text_class': 'text-sky-600 dark:text-sky-400',
#         'title_hover_class': 'group-hover:text-sky-700 dark:group-hover:text-sky-400',
#         'arrow_hover_class': 'group-hover:bg-sky-50 group-hover:text-sky-600 group-hover:border-sky-300 dark:group-hover:bg-sky-500/10 dark:group-hover:text-sky-400 dark:group-hover:border-sky-700',
#         'button_class': 'bg-sky-600 dark:bg-sky-500',
#         'button_hover_class': 'hover:bg-sky-700 dark:hover:bg-sky-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': RoomTypeGroup,
#         'category_model': None,
#         'mapping_model': RoomTypeMapping,
#         'detail_model': None,
#         'group_form': RoomTypeGroupForm,
#         'category_form': None,
#         'mapping_form': RoomTypeMappingForm,
#         'detail_form': None,
#     },
#     'packages': {
#         'key': 'packages',
#         'label': 'Package',
#         'description': 'Organize packages into clear groups so you can measure which offers drive the most bookings and revenue.',
#         'color': 'emerald',
#         'icon': 'fas fa-box-open',
#         'image': None, #'mappings/domains/packages.jpg',
#         'card_border_class': 'hover:border-emerald-300 dark:hover:border-emerald-700',
#         'card_ring_class': 'hover:ring-emerald-200 dark:hover:ring-emerald-800',
#         'top_bar_class': 'bg-emerald-500',
#         'icon_bg_class': 'bg-emerald-100 dark:bg-emerald-500/10',
#         'icon_text_class': 'text-emerald-600 dark:text-emerald-400',
#         'title_hover_class': 'group-hover:text-emerald-700 dark:group-hover:text-emerald-400',
#         'arrow_hover_class': 'group-hover:bg-emerald-50 group-hover:text-emerald-600 group-hover:border-emerald-300 dark:group-hover:bg-emerald-500/10 dark:group-hover:text-emerald-400 dark:group-hover:border-emerald-700',
#         'button_class': 'bg-emerald-600 dark:bg-emerald-500',
#         'button_hover_class': 'hover:bg-emerald-700 dark:hover:bg-emerald-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': PackageGroup,
#         'category_model': None,
#         'mapping_model': PackageMapping,
#         'detail_model': None,
#         'group_form': PackageGroupForm,
#         'category_form': None,
#         'mapping_form': PackageMappingForm,
#         'detail_form': None,
#     },
#     'rate-codes': {
#         'key': 'rate-codes',
#         'label': 'Rate Code',
#         'description': 'Structure rate codes into meaningful groups to track performance and identify the most effective pricing strategies.',
#         'color': 'violet',
#         'icon': 'fas fa-tags',
#         'image': None, #'mappings/domains/rate-codes.jpg',
#         'card_border_class': 'hover:border-violet-300 dark:hover:border-violet-700',
#         'card_ring_class': 'hover:ring-violet-200 dark:hover:ring-violet-800',
#         'top_bar_class': 'bg-violet-500',
#         'icon_bg_class': 'bg-violet-100 dark:bg-violet-500/10',
#         'icon_text_class': 'text-violet-600 dark:text-violet-400',
#         'title_hover_class': 'group-hover:text-violet-700 dark:group-hover:text-violet-400',
#         'arrow_hover_class': 'group-hover:bg-violet-50 group-hover:text-violet-600 group-hover:border-violet-300 dark:group-hover:bg-violet-500/10 dark:group-hover:text-violet-400 dark:group-hover:border-violet-700',
#         'button_class': 'bg-violet-600 dark:bg-violet-500',
#         'button_hover_class': 'hover:bg-violet-700 dark:hover:bg-violet-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': RateCodeGroup,
#         'category_model': None,
#         'mapping_model': RateCodeMapping,
#         'detail_model': None,
#         'group_form': RateCodeGroupForm,
#         'category_form': None,
#         'mapping_form': RateCodeMappingForm,
#         'detail_form': None,
#     },
#     'travel-agents': {
#         'key': 'travel-agents',
#         'label': 'Travel Agent',
#         'description': 'Organize travel agents to evaluate performance, strengthen partnerships, and uncover new business opportunities.',
#         'color': 'cyan',
#         'icon': 'fas fa-plane-departure',
#         'image': None, #'mappings/domains/travel-agents.jpg',
#         'card_border_class': 'hover:border-cyan-300 dark:hover:border-cyan-700',
#         'card_ring_class': 'hover:ring-cyan-200 dark:hover:ring-cyan-800',
#         'top_bar_class': 'bg-cyan-500',
#         'icon_bg_class': 'bg-cyan-100 dark:bg-cyan-500/10',
#         'icon_text_class': 'text-cyan-600 dark:text-cyan-400',
#         'title_hover_class': 'group-hover:text-cyan-700 dark:group-hover:text-cyan-400',
#         'arrow_hover_class': 'group-hover:bg-cyan-50 group-hover:text-cyan-600 group-hover:border-cyan-300 dark:group-hover:bg-cyan-500/10 dark:group-hover:text-cyan-400 dark:group-hover:border-cyan-700',
#         'button_class': 'bg-cyan-600 dark:bg-cyan-500',
#         'button_hover_class': 'hover:bg-cyan-700 dark:hover:bg-cyan-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': TravelAgentGroup,
#         'category_model': None,
#         'mapping_model': TravelAgentMapping,
#         'detail_model': None,
#         'group_form': TravelAgentGroupForm,
#         'category_form': None,
#         'mapping_form': TravelAgentMappingForm,
#         'detail_form': None,
#     },
#     'guest-countries': {
#         'key': 'guest-countries',
#         'label': 'Guest Country',
#         'description': 'See where guests are coming from so marketing efforts can be refined and the right audiences can be targeted.',
#         'color': 'amber',
#         'icon': 'fas fa-globe',
#         'image': None, #'mappings/domains/guest-countries.jpg',
#         'card_border_class': 'hover:border-amber-300 dark:hover:border-amber-700',
#         'card_ring_class': 'hover:ring-amber-200 dark:hover:ring-amber-800',
#         'top_bar_class': 'bg-amber-500',
#         'icon_bg_class': 'bg-amber-100 dark:bg-amber-500/10',
#         'icon_text_class': 'text-amber-600 dark:text-amber-400',
#         'title_hover_class': 'group-hover:text-amber-700 dark:group-hover:text-amber-400',
#         'arrow_hover_class': 'group-hover:bg-amber-50 group-hover:text-amber-600 group-hover:border-amber-300 dark:group-hover:bg-amber-500/10 dark:group-hover:text-amber-400 dark:group-hover:border-amber-700',
#         'button_class': 'bg-amber-600 dark:bg-amber-500',
#         'button_hover_class': 'hover:bg-amber-700 dark:hover:bg-amber-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': GuestCountryGroup,
#         'category_model': None,
#         'mapping_model': GuestCountryMapping,
#         'detail_model': None,
#         'group_form': GuestCountryGroupForm,
#         'category_form': None,
#         'mapping_form': GuestCountryMappingForm,
#         'detail_form': None,
#     },
#     'companies': {
#         'key': 'companies',
#         'label': 'Company',
#         'description': 'Classify reservations by company to support corporate account management and grow the business segment.',
#         'color': 'blue',
#         'icon': 'fas fa-building',
#         'image': None, #'mappings/domains/companies.jpg',
#         'card_border_class': 'hover:border-blue-300 dark:hover:border-blue-700',
#         'card_ring_class': 'hover:ring-blue-200 dark:hover:ring-blue-800',
#         'top_bar_class': 'bg-blue-500',
#         'icon_bg_class': 'bg-blue-100 dark:bg-blue-500/10',
#         'icon_text_class': 'text-blue-600 dark:text-blue-400',
#         'title_hover_class': 'group-hover:text-blue-700 dark:group-hover:text-blue-400',
#         'arrow_hover_class': 'group-hover:bg-blue-50 group-hover:text-blue-600 group-hover:border-blue-300 dark:group-hover:bg-blue-500/10 dark:group-hover:text-blue-400 dark:group-hover:border-blue-700',
#         'button_class': 'bg-blue-600 dark:bg-blue-500',
#         'button_hover_class': 'hover:bg-blue-700 dark:hover:bg-blue-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': CompanyGroup,
#         'category_model': None,
#         'mapping_model': CompanyMapping,
#         'detail_model': None,
#         'group_form': CompanyGroupForm,
#         'category_form': None,
#         'mapping_form': CompanyMappingForm,
#         'detail_form': None,
#     },
#     'day-of-week': {
#         'key': 'day-of-week',
#         'label': 'Day of Week',
#         'description': 'Create weekday and weekend groupings that match business logic for clearer demand analysis.',
#         'color': 'indigo',
#         'icon': 'fas fa-calendar-day',
#         'image': None, #'mappings/domains/day-of-week.jpg',
#         'card_border_class': 'hover:border-indigo-300 dark:hover:border-indigo-700',
#         'card_ring_class': 'hover:ring-indigo-200 dark:hover:ring-indigo-800',
#         'top_bar_class': 'bg-indigo-500',
#         'icon_bg_class': 'bg-indigo-100 dark:bg-indigo-500/10',
#         'icon_text_class': 'text-indigo-600 dark:text-indigo-400',
#         'title_hover_class': 'group-hover:text-indigo-700 dark:group-hover:text-indigo-400',
#         'arrow_hover_class': 'group-hover:bg-indigo-50 group-hover:text-indigo-600 group-hover:border-indigo-300 dark:group-hover:bg-indigo-500/10 dark:group-hover:text-indigo-400 dark:group-hover:border-indigo-700',
#         'button_class': 'bg-indigo-600 dark:bg-indigo-500',
#         'button_hover_class': 'hover:bg-indigo-700 dark:hover:bg-indigo-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': DayOfWeekGroup,
#         'category_model': None,
#         'mapping_model': DayOfWeekMapping,
#         'detail_model': None,
#         'group_form': DayOfWeekGroupForm,
#         'category_form': None,
#         'mapping_form': DayOfWeekMappingForm,
#         'detail_form': None,
#     },
#     'booking-sources': {
#         'key': 'booking-sources',
#         'label': 'Booking Source',
#         'description': 'Organize booking channels like direct, wholesale, and OTA sources to sharpen distribution insights.',
#         'color': 'rose',
#         'icon': 'fas fa-network-wired',
#         'image': None, #'mappings/domains/booking-sources.jpg',
#         'card_border_class': 'hover:border-rose-300 dark:hover:border-rose-700',
#         'card_ring_class': 'hover:ring-rose-200 dark:hover:ring-rose-800',
#         'top_bar_class': 'bg-rose-500',
#         'icon_bg_class': 'bg-rose-100 dark:bg-rose-500/10',
#         'icon_text_class': 'text-rose-600 dark:text-rose-400',
#         'title_hover_class': 'group-hover:text-rose-700 dark:group-hover:text-rose-400',
#         'arrow_hover_class': 'group-hover:bg-rose-50 group-hover:text-rose-600 group-hover:border-rose-300 dark:group-hover:bg-rose-500/10 dark:group-hover:text-rose-400 dark:group-hover:border-rose-700',
#         'button_class': 'bg-rose-600 dark:bg-rose-500',
#         'button_hover_class': 'hover:bg-rose-700 dark:hover:bg-rose-400',
#         'has_group': True,
#         'has_category': True,
#         'has_details': False,
#         'group_model': BookingSourceGroup,
#         'category_model': BookingSourceCategory,
#         'mapping_model': BookingSourceMapping,
#         'detail_model': None,
#         'group_form': BookingSourceGroupForm,
#         'category_form': BookingSourceCategoryForm,
#         'mapping_form': BookingSourceMappingForm,
#         'detail_form': None,
#     },
#     'origins': {
#         'key': 'origins',
#         'label': 'Origin',
#         'description': 'Map reservation origins such as websites and channel managers to improve visibility across the booking journey.',
#         'color': 'teal',
#         'icon': 'fas fa-route',
#         'image': None, #'mappings/domains/origins.jpg',
#         'card_border_class': 'hover:border-teal-300 dark:hover:border-teal-700',
#         'card_ring_class': 'hover:ring-teal-200 dark:hover:ring-teal-800',
#         'top_bar_class': 'bg-teal-500',
#         'icon_bg_class': 'bg-teal-100 dark:bg-teal-500/10',
#         'icon_text_class': 'text-teal-600 dark:text-teal-400',
#         'title_hover_class': 'group-hover:text-teal-700 dark:group-hover:text-teal-400',
#         'arrow_hover_class': 'group-hover:bg-teal-50 group-hover:text-teal-600 group-hover:border-teal-300 dark:group-hover:bg-teal-500/10 dark:group-hover:text-teal-400 dark:group-hover:border-teal-700',
#         'button_class': 'bg-teal-600 dark:bg-teal-500',
#         'button_hover_class': 'hover:bg-teal-700 dark:hover:bg-teal-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': OriginGroup,
#         'category_model': None,
#         'mapping_model': OriginMapping,
#         'detail_model': None,
#         'group_form': OriginGroupForm,
#         'category_form': None,
#         'mapping_form': OriginMappingForm,
#         'detail_form': None,
#     },
#     'competitors': {
#         'key': 'competitors',
#         'label': 'Competitor',
#         'description': 'Set up competitor groups to simplify rate benchmarking and support smarter pricing decisions.',
#         'color': 'red',
#         'icon': 'fas fa-trophy',
#         'image': None, #'mappings/domains/competitors.jpg',
#         'card_border_class': 'hover:border-red-300 dark:hover:border-red-700',
#         'card_ring_class': 'hover:ring-red-200 dark:hover:ring-red-800',
#         'top_bar_class': 'bg-red-500',
#         'icon_bg_class': 'bg-red-100 dark:bg-red-500/10',
#         'icon_text_class': 'text-red-600 dark:text-red-400',
#         'title_hover_class': 'group-hover:text-red-700 dark:group-hover:text-red-400',
#         'arrow_hover_class': 'group-hover:bg-red-50 group-hover:text-red-600 group-hover:border-red-300 dark:group-hover:bg-red-500/10 dark:group-hover:text-red-400 dark:group-hover:border-red-700',
#         'button_class': 'bg-red-600 dark:bg-red-500',
#         'button_hover_class': 'hover:bg-red-700 dark:hover:bg-red-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': CompetitorGroup,
#         'category_model': None,
#         'mapping_model': CompetitorMapping,
#         'detail_model': None,
#         'group_form': CompetitorGroupForm,
#         'category_form': None,
#         'mapping_form': CompetitorMappingForm,
#         'detail_form': None,
#     },
#     'loyalties': {
#         'key': 'loyalties',
#         'label': 'Loyalty',
#         'description': 'Organize loyalty data into meaningful tiers or groups to better understand member value and engagement.',
#         'color': 'pink',
#         'icon': 'fas fa-crown',
#         'image': None, #'mappings/domains/loyalties.jpg',
#         'card_border_class': 'hover:border-pink-300 dark:hover:border-pink-700',
#         'card_ring_class': 'hover:ring-pink-200 dark:hover:ring-pink-800',
#         'top_bar_class': 'bg-pink-500',
#         'icon_bg_class': 'bg-pink-100 dark:bg-pink-500/10',
#         'icon_text_class': 'text-pink-600 dark:text-pink-400',
#         'title_hover_class': 'group-hover:text-pink-700 dark:group-hover:text-pink-400',
#         'arrow_hover_class': 'group-hover:bg-pink-50 group-hover:text-pink-600 group-hover:border-pink-300 dark:group-hover:bg-pink-500/10 dark:group-hover:text-pink-400 dark:group-hover:border-pink-700',
#         'button_class': 'bg-pink-600 dark:bg-pink-500',
#         'button_hover_class': 'hover:bg-pink-700 dark:hover:bg-pink-400',
#         'has_group': True,
#         'has_category': False,
#         'has_details': False,
#         'group_model': LoyaltyGroup,
#         'category_model': None,
#         'mapping_model': LoyaltyMapping,
#         'detail_model': None,
#         'group_form': LoyaltyGroupForm,
#         'category_form': None,
#         'mapping_form': LoyaltyMappingForm,
#         'detail_form': None,
#     },

# }

# def get_mapping_domain(domain_key):
#     config = MAPPING_DOMAIN_REGISTRY[domain_key].copy()
#     config.setdefault('has_group', True)
#     config.setdefault('has_category', False)
#     config.setdefault('has_details', False)
#     config.setdefault('group_model', None)
#     config.setdefault('category_model', None)
#     config.setdefault('mapping_model', None)
#     config.setdefault('detail_model', None)
#     config.setdefault('group_form', None)
#     config.setdefault('category_form', None)
#     config.setdefault('mapping_form', None)
#     config.setdefault('detail_form', None)

#     config.setdefault('color', 'orange')
#     config.setdefault('icon', 'fas fa-folder')
#     config.setdefault('image', None)
#     config.setdefault('card_border_class', 'hover:border-orange-300 dark:hover:border-orange-700')
#     config.setdefault('card_ring_class', 'hover:ring-orange-200 dark:hover:ring-orange-800')
#     config.setdefault('top_bar_class', 'bg-orange-500')
#     config.setdefault('icon_bg_class', 'bg-orange-100 dark:bg-orange-500/10')
#     config.setdefault('icon_text_class', 'text-orange-600 dark:text-orange-400')
#     config.setdefault('title_hover_class', 'group-hover:text-orange-700 dark:group-hover:text-orange-400')
#     config.setdefault('arrow_hover_class', 'group-hover:bg-orange-50 group-hover:text-orange-600 group-hover:border-orange-300 dark:group-hover:bg-orange-500/10 dark:group-hover:text-orange-400 dark:group-hover:border-orange-700')
#     config.setdefault('button_class', 'bg-orange-600 dark:bg-orange-500')
#     config.setdefault('button_hover_class', 'hover:bg-orange-700 dark:hover:bg-orange-400')
#     return config









# # from apps.settings.mappings.forms.common import (
# #     RoomTypeGroupForm,
# #     RoomTypeMappingForm,
# #     PackageGroupForm,
# #     PackageMappingForm,
# #     RateCodeGroupForm,
# #     RateCodeMappingForm,
# #     TravelAgentGroupForm,
# #     TravelAgentMappingForm,
# #     GuestCountryGroupForm,
# #     GuestCountryMappingForm,
# #     CompanyGroupForm,
# #     CompanyMappingForm,
# #     DayOfWeekGroupForm,
# #     DayOfWeekMappingForm,
# #     BookingSourceGroupForm,
# #     BookingSourceMappingForm,
# #     OriginGroupForm,
# #     OriginMappingForm,
# #     CompetitorGroupForm,
# #     CompetitorMappingForm,
# #     LoyaltyGroupForm,
# #     LoyaltyMappingForm,
# # )
# # from apps.settings.mappings.models import (
# #     RoomTypeGroup,
# #     RoomTypeMapping,
# #     PackageGroup,
# #     PackageMapping,
# #     RateCodeGroup,
# #     RateCodeMapping,
# #     TravelAgentGroup,
# #     TravelAgentMapping,
# #     GuestCountryGroup,
# #     GuestCountryMapping,
# #     CompanyGroup,
# #     CompanyMapping,
# #     DayOfWeekGroup,
# #     DayOfWeekMapping,
# #     BookingSourceGroup,
# #     BookingSourceMapping,
# #     OriginGroup,
# #     OriginMapping,
# #     CompetitorGroup,
# #     CompetitorMapping,
# #     LoyaltyGroup,
# #     LoyaltyMapping,
# # )

# # MAPPING_DOMAIN_REGISTRY = {
# #     'room-types': {
# #         'label': 'Room Type',
# #         'description': 'Define room categories and pricing relationships to keep inventory structured and easy to analyze.',
# #         'group_model': RoomTypeGroup,
# #         'mapping_model': RoomTypeMapping,
# #         'group_form': RoomTypeGroupForm,
# #         'mapping_form': RoomTypeMappingForm,
# #     },
# #     'packages': {
# #         'label': 'Package',
# #         'description': 'Organize packages into clear groups so you can measure which offers drive the most bookings and revenue.',
# #         'group_model': PackageGroup,
# #         'mapping_model': PackageMapping,
# #         'group_form': PackageGroupForm,
# #         'mapping_form': PackageMappingForm,
# #     },
# #     'rate-codes': {
# #         'label': 'Rate Code',
# #         'description': 'Structure rate codes into meaningful groups to track performance and identify the most effective pricing strategies.',
# #         'group_model': RateCodeGroup,
# #         'mapping_model': RateCodeMapping,
# #         'group_form': RateCodeGroupForm,
# #         'mapping_form': RateCodeMappingForm,
# #     },
# #     'travel-agents': {
# #         'label': 'Travel Agent',
# #         'description': 'Organize travel agents to evaluate performance, strengthen partnerships, and uncover new business opportunities.',
# #         'group_model': TravelAgentGroup,
# #         'mapping_model': TravelAgentMapping,
# #         'group_form': TravelAgentGroupForm,
# #         'mapping_form': TravelAgentMappingForm,
# #     },
# #     'guest-countries': {
# #         'label': 'Guest Country',
# #         'description': 'See where guests are coming from so marketing efforts can be refined and the right audiences can be targeted.',
# #         'group_model': GuestCountryGroup,
# #         'mapping_model': GuestCountryMapping,
# #         'group_form': GuestCountryGroupForm,
# #         'mapping_form': GuestCountryMappingForm,
# #     },
# #     'companies': {
# #         'label': 'Company',
# #         'description': 'Classify reservations by company to support corporate account management and grow the business segment.',
# #         'group_model': CompanyGroup,
# #         'mapping_model': CompanyMapping,
# #         'group_form': CompanyGroupForm,
# #         'mapping_form': CompanyMappingForm,
# #     },
# #     'day-of-week': {
# #         'label': 'Day of Week',
# #         'description': 'Create weekday and weekend groupings that match business logic for clearer demand analysis.',
# #         'group_model': DayOfWeekGroup,
# #         'mapping_model': DayOfWeekMapping,
# #         'group_form': DayOfWeekGroupForm,
# #         'mapping_form': DayOfWeekMappingForm,
# #     },
# #     'booking-sources': {
# #         'label': 'Booking Source',
# #         'description': 'Organize booking channels like direct, wholesale, and OTA sources to sharpen distribution insights.',
# #         'group_model': BookingSourceGroup,
# #         'mapping_model': BookingSourceMapping,
# #         'group_form': BookingSourceGroupForm,
# #         'mapping_form': BookingSourceMappingForm,
# #     },
# #     'origins': {
# #         'label': 'Origin',
# #         'description': 'Map reservation origins such as websites and channel managers to improve visibility across the booking journey.',
# #         'group_model': OriginGroup,
# #         'mapping_model': OriginMapping,
# #         'group_form': OriginGroupForm,
# #         'mapping_form': OriginMappingForm,
# #     },
# #     'competitors': {
# #         'label': 'Competitor',
# #         'description': 'Set up competitor groups to simplify rate benchmarking and support smarter pricing decisions.',
# #         'group_model': CompetitorGroup,
# #         'mapping_model': CompetitorMapping,
# #         'group_form': CompetitorGroupForm,
# #         'mapping_form': CompetitorMappingForm,
# #     },
# #     'loyalties': {
# #         'label': 'Loyalty',
# #         'description': 'Organize loyalty data into meaningful tiers or groups to better understand member value and engagement.',
# #         'group_model': LoyaltyGroup,
# #         'mapping_model': LoyaltyMapping,
# #         'group_form': LoyaltyGroupForm,
# #         'mapping_form': LoyaltyMappingForm,
# #     },
# # }

# # def get_mapping_domain(domain_key):
# #     return MAPPING_DOMAIN_REGISTRY[domain_key]
