# Generated by Django 6.0.3 on 2026-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpectedFileDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("file_type", models.CharField(max_length=60)),
                ("expected_pattern", models.CharField(blank=True, max_length=140)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("destination_table", models.CharField(blank=True, max_length=120)),
                ("expected_by_hour", models.PositiveSmallIntegerField(default=8)),
                ("is_critical", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dataops_expected_file_definitions",
                "ordering": ["property__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="FileDownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("source_workflow", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "dataops_file_download_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=80)),
                ("status_from", models.CharField(blank=True, max_length=30)),
                ("status_to", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField(blank=True)),
                ("actor_type", models.CharField(default="system", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "dataops_file_event_logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("missing", "Missing"),
                            ("received", "Received"),
                            ("validated", "Validated"),
                            ("processing", "Processing"),
                            ("loaded", "Loaded to database"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                            ("downloaded", "Downloaded"),
                        ],
                        db_index=True,
                        default="expected",
                        max_length=30,
                    ),
                ),
                ("expected_for_date", models.DateField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("checksum", models.CharField(blank=True, max_length=140)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("storage_path", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "dataops_file_records",
                "ordering": ["-created_at"],
                "permissions": [("download_filerecord", "Can download file content and metadata")],
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_reference", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("destination_table", models.CharField(blank=True, max_length=120)),
                ("processing_duration_seconds", models.PositiveIntegerField(default=0)),
                ("transformation_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "dataops_ingestion_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoadResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("destination_table", models.CharField(max_length=120)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("inserted_records", models.PositiveIntegerField(default=0)),
                ("updated_records", models.PositiveIntegerField(default=0)),
                ("rejected_records", models.PositiveIntegerField(default=0)),
                ("duplicate_records", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
            ],
            options={
                "db_table": "dataops_load_results",
            },
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("connection_type", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "db_table": "dataops_source_systems",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_valid", models.BooleanField(default=False)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "dataops_validation_results",
            },
        ),
    ]
