# Generated by Django 6.0.3 on 2026-04-04 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notificationsannouncements", "0001_initial"),
        ("propertycore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="properties",
            field=models.ManyToManyField(
                blank=True, related_name="announcements", to="propertycore.property"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcementacknowledgement",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledgements",
                to="notificationsannouncements.announcement",
            ),
        ),
        migrations.AddField(
            model_name="announcementacknowledgement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcement_acknowledgements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementacknowledgement",
            unique_together={("announcement", "user")},
        ),
    ]
