# Generated by Django 6.0.3 on 2026-04-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("propertycore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_date", models.DateField(db_index=True)),
                ("available_rooms", models.PositiveIntegerField(default=0)),
                ("rooms_sold", models.PositiveIntegerField(default=0)),
                ("room_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("revenue_goal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("occupancy_goal", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="propertycore.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property daily metric",
                "verbose_name_plural": "Property daily metrics",
                "db_table": "analytics_property_daily_metrics",
                "ordering": ["property__name", "-metric_date"],
                "unique_together": {("property", "metric_date")},
            },
        ),
    ]
