# Generated by Django 6.0.3 on 2026-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roi_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["file_record_id"], name="roi_daily_file_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["property_id"], name="roi_daily_property_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["snapshot_date"], name="roi_daily_snapshot_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["reservation_id"], name="roi_daily_reservation_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["detail_type"], name="roi_daily_type_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationdailystage",
            index=models.Index(fields=["row_hash"], name="roi_daily_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["file_record_id"], name="roi_res_file_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["property_id"], name="roi_res_property_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["snapshot_date"], name="roi_res_snapshot_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["business_date"], name="roi_res_business_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["reservation_id"], name="roi_res_reservation_idx"),
        ),
        migrations.AddIndex(
            model_name="roireservationstage",
            index=models.Index(fields=["row_hash"], name="roi_res_hash_idx"),
        ),
    ]
