RESERVATION_DETAILS_HEADERS = [
    "name_id",
    "membership_id",
    "business_date_created",
    "trunc_end_date",
    "insert_date",
    "update_date",
    "cancellation_date",
    "confirmation_no",
    "cancellation_reason_code",
    "channel",
    "country",
    "state",
    "city",
    "guarantee_code",
    "guarantee_code_pre_ci",
    "payment_method",
    "purpose_of_stay",
    "commission_paid",
    "commission_payout_to",
    "gender",
    "nationality",
    "title",
]

DAILY_HEADERS = {
    "RDEN_ACCOUNTS": [
        "day_offset",
        "resv_daily_el_seq",
        "reservation_date",
        "company",
        "company_id",
        "travel_agent",
        "travel_agent_code",
        "industry_code",
        "source",
        "source_code",
    ],
    "RDEN_CODES": [
        "day_offset",
        "rate_code",
        "currency_code",
        "adults",
        "children",
        "share_amount",
    ],
    "RDE_MARKET_CHANNEL": [
        "day_offset",
        "allotment_header_id",
        "resv_daily_el_seq",
        "reservation_date",
        "market_code",
        "origin_of_booking",
    ],
    "RDE_CATEGORIES": [
        "day_offset",
        "room",
        "room_category",
        "booked_room_category",
        "room_class",
        "day_use_yn",
        "due_out_yn",
        "rate_amount",
    ],
    "RES_SUMMARY_1": [
        "day_offset",
        "allotment_header_id",
        "business_date",
        "arr_rooms",
        "dep_rooms",
        "adults",
        "children",
        "no_rooms",
        "single_occupancy",
        "room_revenue",
        "food_revenue",
    ],
    "RES_SUMMARY_2": [
        "day_offset",
        "other_revenue",
        "non_revenue",
        "total_revenue",
        "room_revenue_tax",
        "food_revenue_tax",
        "other_revenue_tax",
        "non_revenue_tax",
        "total_revenue_tax",
        "fc_room_revenue_ratio",
        "day_use_rooms",
    ],
    "RES_SUMMARY_3": [
        "day_offset",
        "package_food_revenue",
        "total_package_revenue",
        "booking_status",
        "block_status",
        "remaining_block_rooms",
        "pickedup_block_rooms",
    ],
    "RES_STAT_1": [
        "day_offset",
        "allotment_header_id",
        "business_date",
        "arr_rooms",
        "dep_rooms",
        "adults",
        "children",
        "nights",
        "single_occupancy",
        "room_revenue",
        "food_revenue",
    ],
    "RES_STAT_2": [
        "day_offset",
        "other_revenue",
        "non_revenue",
        "total_revenue",
        "room_revenue_tax",
        "food_revenue_tax",
        "other_revenue_tax",
        "non_revenue_tax",
        "total_revenue_tax",
        "fc_room_revenue_ratio",
    ],
    "RES_STAT_3": [
        "day_offset",
        "day_use_rooms",
        "package_food_revenue",
        "total_package_revenue",
        "cancelled_rooms",
        "no_show_rooms",
        "no_of_stays",
    ],
}

ROI_SNAPSHOT_NAME = "ROI_DAILY"
DUBAI_TIMEZONE = "Asia/Dubai"
