# Generated by Django 6.0.3 on 2026-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingSourceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Booking Source group",
                "verbose_name_plural": "Booking Source groups",
                "db_table": "settings_booking_sources_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BookingSourceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Booking Source mapping",
                "verbose_name_plural": "Booking Source mappings",
                "db_table": "settings_booking_sources_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="CompanyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Company group",
                "verbose_name_plural": "Company groups",
                "db_table": "settings_companies_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Company mapping",
                "verbose_name_plural": "Company mappings",
                "db_table": "settings_companies_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Competitor group",
                "verbose_name_plural": "Competitor groups",
                "db_table": "settings_competitors_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Competitor mapping",
                "verbose_name_plural": "Competitor mappings",
                "db_table": "settings_competitors_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="DayOfWeekGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Day of Week group",
                "verbose_name_plural": "Day of Week groups",
                "db_table": "settings_day_of_week_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DayOfWeekMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Day of Week mapping",
                "verbose_name_plural": "Day of Week mappings",
                "db_table": "settings_day_of_week_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="GuestCountryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Guest Country group",
                "verbose_name_plural": "Guest Country groups",
                "db_table": "settings_guest_countries_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuestCountryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Guest Country mapping",
                "verbose_name_plural": "Guest Country mappings",
                "db_table": "settings_guest_countries_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Loyalty group",
                "verbose_name_plural": "Loyalty groups",
                "db_table": "settings_loyalties_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Loyalty mapping",
                "verbose_name_plural": "Loyalty mappings",
                "db_table": "settings_loyalties_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="OriginGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Origin group",
                "verbose_name_plural": "Origin groups",
                "db_table": "settings_origins_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OriginMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Origin mapping",
                "verbose_name_plural": "Origin mappings",
                "db_table": "settings_origins_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="PackageGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Package group",
                "verbose_name_plural": "Package groups",
                "db_table": "settings_packages_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Package mapping",
                "verbose_name_plural": "Package mappings",
                "db_table": "settings_packages_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="RateCodeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Rate Code group",
                "verbose_name_plural": "Rate Code groups",
                "db_table": "settings_rate_codes_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RateCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Rate Code mapping",
                "verbose_name_plural": "Rate Code mappings",
                "db_table": "settings_rate_codes_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="RoomTypeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Room Type group",
                "verbose_name_plural": "Room Type groups",
                "db_table": "settings_room_types_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Room Type mapping",
                "verbose_name_plural": "Room Type mappings",
                "db_table": "settings_room_types_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "settings_segments",
                "ordering": [
                    "property__name",
                    "group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="SegmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "settings_segment_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SegmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "settings_segment_details",
                "ordering": ["property__name", "segment__sort_order", "sort_order", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="SegmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "settings_segment_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TravelAgentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Travel Agent group",
                "verbose_name_plural": "Travel Agent groups",
                "db_table": "settings_travel_agents_groups",
                "ordering": ["property__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TravelAgentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("source_code", models.CharField(max_length=80)),
                ("source_label", models.CharField(blank=True, max_length=160)),
                ("mapped_code", models.CharField(blank=True, max_length=80)),
                ("mapped_label", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Travel Agent mapping",
                "verbose_name_plural": "Travel Agent mappings",
                "db_table": "settings_travel_agents_mappings",
                "ordering": ["property__name", "sort_order", "source_code"],
            },
        ),
    ]
