# Generated by Django 6.0.3 on 2026-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsourcegroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingsourcegroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingsourcegroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companygroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companygroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="competitorgroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competitorgroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competitorgroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="dayofweekgroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweekgroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweekgroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="guestcountrygroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guestcountrygroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guestcountrygroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="loyaltygroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loyaltygroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loyaltygroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="origingroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="origingroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="origingroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="packagegroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagegroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagegroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="ratecodegroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ratecodegroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ratecodegroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="roomtypegroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomtypegroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomtypegroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="segment",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segment",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="segmentcategory",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentcategory",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="segmentgroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentgroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentgroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="travelagentgroup",
            name="color",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelagentgroup",
            name="icon",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelagentgroup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
    ]
