# Generated by Django 6.0.3 on 2026-04-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0005_alter_bookingsourcegroup_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segment",
            options={"ordering": ["property__name", "sort_order", "name"]},
        ),
        migrations.AlterField(
            model_name="segment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="settingsmappings.segmentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="settingsmappings.segmentgroup",
            ),
        ),
    ]
