# Generated by Django 6.0.3 on 2026-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0008_alter_bookingsourcemapping_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="dayofweekmapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dayofweekmapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="dayofweekmapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="segmentdetail",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="segmentdetail",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="segmentdetail",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="source_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="source_label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
