# Generated by Django 6.0.3 on 2026-04-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0009_alter_bookingsourcemapping_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentdetail",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="details",
                to="settingsmappings.segment",
            ),
        ),
    ]
