# Generated by Django 6.0.3 on 2026-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0010_alter_segmentdetail_segment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segment",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ]
            },
        ),
        migrations.RemoveField(
            model_name="segment",
            name="group",
        ),
    ]
