# Generated by Django 6.0.3 on 2026-04-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0011_alter_segment_options_remove_segment_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="settingsmappings.segmentcategory",
            ),
        ),
    ]
