# Generated by Django 6.0.3 on 2026-04-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propertycore", "0003_set_property_id_sequence"),
        ("settingsmappings", "0012_alter_segment_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingsourcemapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Booking Source mapping",
                "verbose_name_plural": "Booking Source mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="companymapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Company mapping",
                "verbose_name_plural": "Company mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="competitormapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Competitor mapping",
                "verbose_name_plural": "Competitor mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="dayofweekmapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Day of Week mapping",
                "verbose_name_plural": "Day of Week mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="guestcountrymapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Guest Country mapping",
                "verbose_name_plural": "Guest Country mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltymapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Loyalty mapping",
                "verbose_name_plural": "Loyalty mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="originmapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Origin mapping",
                "verbose_name_plural": "Origin mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="packagemapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Package mapping",
                "verbose_name_plural": "Package mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="ratecodemapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Rate Code mapping",
                "verbose_name_plural": "Rate Code mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtypemapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Room Type mapping",
                "verbose_name_plural": "Room Type mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="segmentdetail",
            options={"ordering": ["property__name", "segment__sort_order", "sort_order", "code"]},
        ),
        migrations.AlterModelOptions(
            name="travelagentmapping",
            options={
                "ordering": ["property__name", "sort_order", "code"],
                "verbose_name": "Travel Agent mapping",
                "verbose_name_plural": "Travel Agent mappings",
            },
        ),
        migrations.RenameField(
            model_name="bookingsourcemapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="bookingsourcemapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="bookingsourcemapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="companymapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="companymapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="companymapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="competitormapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="competitormapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="competitormapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="dayofweekmapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="dayofweekmapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="dayofweekmapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="guestcountrymapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="guestcountrymapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="guestcountrymapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="loyaltymapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="loyaltymapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="loyaltymapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="originmapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="originmapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="originmapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="packagemapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="packagemapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="packagemapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="ratecodemapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="ratecodemapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="ratecodemapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="roomtypemapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="roomtypemapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="roomtypemapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="segmentdetail",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="segmentdetail",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="segmentdetail",
            old_name="source_label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="travelagentmapping",
            old_name="source_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="travelagentmapping",
            old_name="source_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="travelagentmapping",
            old_name="source_label",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="bookingsourcemapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="companymapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="competitormapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="dayofweekmapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="guestcountrymapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="loyaltymapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="originmapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="packagemapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="ratecodemapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="roomtypemapping",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="segmentdetail",
            unique_together={("property", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="travelagentmapping",
            unique_together={("property", "code")},
        ),
    ]
