# Generated by Django 6.0.3 on 2026-04-16 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertycore", "0003_set_property_id_sequence"),
        ("settingsmappings", "0013_alter_bookingsourcemapping_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingsourcemapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "code",
                ],
                "verbose_name": "Booking Source",
                "verbose_name_plural": "Booking Sources",
            },
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="group",
        ),
        migrations.AlterModelTable(
            name="bookingsourcemapping",
            table="settings_booking_sources",
        ),
        migrations.CreateModel(
            name="BookingSourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("color", models.CharField(blank=True, max_length=140, null=True)),
                ("icon", models.CharField(blank=True, max_length=140, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="mappings/images/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.bookingsourcegroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Source category",
                "verbose_name_plural": "Booking Source categories",
                "db_table": "settings_booking_sources_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="bookingsourcemapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_sources",
                to="settingsmappings.bookingsourcecategory",
            ),
        ),
    ]
