# Generated by Django 6.0.3 on 2026-04-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0014_alter_bookingsourcemapping_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segmentdetail",
            options={"ordering": ["property__name", "mapping__sort_order", "sort_order", "code"]},
        ),
        migrations.RenameField(
            model_name="segmentdetail",
            old_name="segment",
            new_name="mapping",
        ),
        migrations.RemoveField(
            model_name="bookingsourcecategory",
            name="color",
        ),
        migrations.RemoveField(
            model_name="bookingsourcecategory",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="bookingsourcecategory",
            name="image",
        ),
    ]
