# Generated by Django 6.0.3 on 2026-04-17 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataopsfiles", "0002_initial"),
        ("propertycore", "0003_set_property_id_sequence"),
        ("settingsmappings", "0015_alter_segmentdetail_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Segment",
            new_name="SegmentMapping",
        ),
        migrations.AlterModelOptions(
            name="bookingsourcemapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Booking Source mapping",
                "verbose_name_plural": "Booking Source mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="companymapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Company mapping",
                "verbose_name_plural": "Company mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="competitormapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Competitor mapping",
                "verbose_name_plural": "Competitor mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="guestcountrymapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Guest Country mapping",
                "verbose_name_plural": "Guest Country mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltymapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Loyalty mapping",
                "verbose_name_plural": "Loyalty mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="originmapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Origin mapping",
                "verbose_name_plural": "Origin mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="packagemapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Package mapping",
                "verbose_name_plural": "Package mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="ratecodemapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Rate Code mapping",
                "verbose_name_plural": "Rate Code mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtypemapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Room Type mapping",
                "verbose_name_plural": "Room Type mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="travelagentmapping",
            options={
                "ordering": [
                    "property__name",
                    "category__group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Travel Agent mapping",
                "verbose_name_plural": "Travel Agent mappings",
            },
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="bookingsourcemapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="companymapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="competitormapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="guestcountrymapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="loyaltymapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="originmapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="packagemapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="roomtypemapping",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="effective_from",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="effective_to",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="group",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="is_review_required",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="travelagentmapping",
            name="source_system",
        ),
        migrations.AddField(
            model_name="bookingsourcemapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="bookingsourcemapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="bookingsourcemapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="companymapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="companymapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="companymapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="competitormapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="competitormapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="competitormapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="guestcountrymapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="guestcountrymapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="guestcountrymapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="loyaltymapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="loyaltymapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="loyaltymapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="originmapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="originmapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="originmapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="packagemapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="packagemapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="packagemapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="ratecodemapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="ratecodemapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="ratecodemapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="roomtypemapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="roomtypemapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="roomtypemapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AddField(
            model_name="travelagentmapping",
            name="color",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="travelagentmapping",
            name="icon",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="travelagentmapping",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mappings/images/"),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.bookingsourcecategory",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingsourcemapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companymapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competitormapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guestcountrymapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loyaltymapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="originmapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="packagemapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ratecodemapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomtypemapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="code",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelagentmapping",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="bookingsourcemapping",
            table="settings_booking_sources_mappings",
        ),
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.companygroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company category",
                "verbose_name_plural": "Company categories",
                "db_table": "settings_companies_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="companymapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.companycategory",
            ),
        ),
        migrations.CreateModel(
            name="CompetitorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.competitorgroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor category",
                "verbose_name_plural": "Competitor categories",
                "db_table": "settings_competitors_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="competitormapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.competitorcategory",
            ),
        ),
        migrations.CreateModel(
            name="GuestCountryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.guestcountrygroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Country category",
                "verbose_name_plural": "Guest Country categories",
                "db_table": "settings_guest_countries_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="guestcountrymapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.guestcountrycategory",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.loyaltygroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty category",
                "verbose_name_plural": "Loyalty categories",
                "db_table": "settings_loyalties_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="loyaltymapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.loyaltycategory",
            ),
        ),
        migrations.CreateModel(
            name="OriginCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.origingroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Origin category",
                "verbose_name_plural": "Origin categories",
                "db_table": "settings_origins_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="originmapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.origincategory",
            ),
        ),
        migrations.CreateModel(
            name="PackageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.packagegroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Package category",
                "verbose_name_plural": "Package categories",
                "db_table": "settings_packages_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="packagemapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.packagecategory",
            ),
        ),
        migrations.CreateModel(
            name="RateCodeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.ratecodegroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Code category",
                "verbose_name_plural": "Rate Code categories",
                "db_table": "settings_rate_codes_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="ratecodemapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.ratecodecategory",
            ),
        ),
        migrations.CreateModel(
            name="RoomTypeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.roomtypegroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Type category",
                "verbose_name_plural": "Room Type categories",
                "db_table": "settings_room_types_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="roomtypemapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.roomtypecategory",
            ),
        ),
        migrations.CreateModel(
            name="TravelAgentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settingsmappings.travelagentgroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Agent category",
                "verbose_name_plural": "Travel Agent categories",
                "db_table": "settings_travel_agents_categories",
                "ordering": ["property__name", "group__sort_order", "sort_order", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.AddField(
            model_name="travelagentmapping",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="settingsmappings.travelagentcategory",
            ),
        ),
        migrations.CreateModel(
            name="BookingSourceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.bookingsourcemapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Source detail",
                "verbose_name_plural": "Booking Source details",
                "db_table": "settings_booking_source_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="CompanyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.companymapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company detail",
                "verbose_name_plural": "Company details",
                "db_table": "settings_company_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="CompetitorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.competitormapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor detail",
                "verbose_name_plural": "Competitor details",
                "db_table": "settings_competitor_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="GuestCountryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.guestcountrymapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Country detail",
                "verbose_name_plural": "Guest Country details",
                "db_table": "settings_guest_country_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="LoyaltyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.loyaltymapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty detail",
                "verbose_name_plural": "Loyalty details",
                "db_table": "settings_loyalty_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="OriginDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.originmapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Origin detail",
                "verbose_name_plural": "Origin details",
                "db_table": "settings_origin_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="PackageDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.packagemapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Package detail",
                "verbose_name_plural": "Package details",
                "db_table": "settings_package_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="RateCodeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.ratecodemapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Code detail",
                "verbose_name_plural": "Rate Code details",
                "db_table": "settings_rate_code_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="RoomTypeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.roomtypemapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Type detail",
                "verbose_name_plural": "Room Type details",
                "db_table": "settings_room_type_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="TravelAgentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                ("description", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_review_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settingsmappings.travelagentmapping",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="propertycore.property",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="dataopsfiles.sourcesystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Agent detail",
                "verbose_name_plural": "Travel Agent details",
                "db_table": "settings_travel_agent_details",
                "ordering": ["property__name", "mapping__sort_order", "sort_order", "code"],
                "unique_together": {("property", "code")},
            },
        ),
    ]
