# Generated by Django 6.0.3 on 2026-04-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0016_rename_segment_segmentmapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtypedetail",
            name="number_of_rooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomtypedetail",
            name="room_category",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomtypedetail",
            name="room_class",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
