# Generated by Django 6.0.3 on 2026-04-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0017_roomtypedetail_number_of_rooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecodedetail",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_code_details",
                to="settingsmappings.origindetail",
            ),
        ),
        migrations.AddField(
            model_name="ratecodedetail",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_code_details",
                to="settingsmappings.segmentdetail",
            ),
        ),
    ]
