# Generated by Django 6.0.3 on 2026-04-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0018_ratecodedetail_origin_ratecodedetail_segment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratecodemapping",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="ratecodegroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ratecodegroup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ratecodegroup",
            name="property",
        ),
        migrations.RemoveField(
            model_name="ratecodegroup",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="ratecodemapping",
            options={
                "ordering": ["property__name", "segment__sort_order", "sort_order", "name"],
                "verbose_name": "Rate Code mapping",
                "verbose_name_plural": "Rate Code mappings",
            },
        ),
        migrations.RemoveField(
            model_name="ratecodedetail",
            name="segment",
        ),
        migrations.AddField(
            model_name="ratecodemapping",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_code_mappings",
                to="settingsmappings.segmentdetail",
            ),
        ),
        migrations.AlterField(
            model_name="ratecodedetail",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_code_details",
                to="settingsmappings.ratecodemapping",
            ),
        ),
        migrations.DeleteModel(
            name="RateCodeCategory",
        ),
        migrations.DeleteModel(
            name="RateCodeGroup",
        ),
    ]
