# Generated by Django 6.0.3 on 2026-04-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0019_remove_ratecodemapping_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratecodemapping",
            options={
                "ordering": ["property__name", "category__sort_order", "sort_order", "name"],
                "verbose_name": "Rate Code mapping",
                "verbose_name_plural": "Rate Code mappings",
            },
        ),
        migrations.RenameField(
            model_name="ratecodemapping",
            old_name="segment",
            new_name="category",
        ),
    ]
