# Generated by Django 6.0.3 on 2026-04-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsmappings", "0020_alter_ratecodemapping_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratecodedetail",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_code_details",
                to="settingsmappings.segmentdetail",
            ),
        ),
        migrations.DeleteModel(
            name="RateCodeMapping",
        ),
    ]
