# Generated by Django 6.0.3 on 2026-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                ("timezone", models.CharField(default="Asia/Dubai", max_length=80)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=20)),
                ("bio", models.TextField(blank=True)),
                ("receive_email_notifications", models.BooleanField(default=True)),
                ("receive_product_announcements", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
