# Generated by Django 6.0.3 on 2026-04-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("hotel_group", "Hotel Group"),
                            ("restaurant_group", "Restaurant Group"),
                            ("hospitality", "Hospitality"),
                            ("merchant", "Merchant"),
                        ],
                        default="hospitality",
                        max_length=40,
                    ),
                ),
                ("headquarters_city", models.CharField(blank=True, max_length=80)),
                ("headquarters_country", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("resort", "Resort"),
                            ("apartment", "Apartment"),
                            ("cluster", "Cluster"),
                        ],
                        default="hotel",
                        max_length=40,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("currency", models.CharField(default="AED", max_length=10)),
                ("timezone", models.CharField(default="Asia/Dubai", max_length=80)),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="propertycore.organization",
                    ),
                ),
            ],
            options={
                "db_table": "properties",
                "ordering": ["organization__name", "name"],
                "permissions": [
                    ("view_dashboard", "Can view business dashboards"),
                    ("view_reports", "Can view embedded reports"),
                    ("view_dataops", "Can view data operations"),
                    ("manage_mappings", "Can manage mapping settings"),
                ],
            },
        ),
    ]
