# Generated by Django 6.0.3 on 2026-04-12 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertycore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="resort",
            field=models.CharField(default=django.utils.timezone.now, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
