# Generated by Django 6.0.3 on 2026-04-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propertycore", "0002_property_resort"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER SEQUENCE core.properties_id_seq RESTART WITH 1000;
            """,
            reverse_sql="""
                ALTER SEQUENCE core.properties_id_seq RESTART WITH 1;
            """,
        ),
    ]