SELECT resort
, rate_code
, rate_class
, rate_category
, los_unit
, description
, flat_or_percentage
, operator_type
, base_rate_code
, alternate_rate_code
, commission_code
, label
, market_code
, source_code
, trx_code
, currency_code
, profit_trx_code
, negotiated
, weekend_days
, rate_bucket
, max_los
, addition
, multiplication
, rate_code_locked
, inactive_date
, insert_date
, update_date
, yield_as
, base_flt_pct
, base_rounding
, base_amount
, bfst_price
, package_yn
, commission_yn
, rate_includes_tax_yn
, yieldable_yn
, dayuse_yn
, trx_code_wk
, pkg_trx_code
, trx_tax_incl_yn
, pkg_trx_code_wk
, trx_wk_tax_incl_yn
, pkg_trx_tax_incl_yn
, pkg_trx_wk_tax_incl_yn
, complimentary_yn
, house_use_yn
, rate_calendar_yn
, gds_allowed_yn
, loyalty_program_yn
, redemption_rate_yn
, distribute_yn
, tiered_yn
, bfst_incl_yn
, tax_included_yn
, tax_included_perc
FROM stg.rate_header;